name: Pull request notification to Telegram

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          MESSAGE="🔔 A Pull Request has been ${{ github.event.action }}\\!

          *PR Number*: ${{ github.event.pull_request.number }}
          *PR Title*: ${{ github.event.pull_request.title }}
          *PR Author*: ${{ github.event.pull_request.user.login }}

          Check out the PR details below\\."

          ESCAPED_MESSAGE=$(echo "$MESSAGE" | sed 's/[_*[\]()~`>#+\-=|{}.!]/\\&/g')

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="$ESCAPED_MESSAGE" \
          -d parse_mode="MarkdownV2" \
          -d "reply_markup={\"inline_keyboard\":[[{\"text\":\"View Pull Request\",\"url\":\"${{ github.event.pull_request.html_url }}\"}]]}"
